name: CI Build & FTP Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Debug dist
        run: ls -R dist || true
      - name: Validate required secrets
        run: |
          missing=0
          [ -n "${{ secrets.FTP_HOST }}" ] || { echo "::error::Missing secret FTP_HOST"; missing=1; }
          [ -n "${{ secrets.FTP_USERNAME }}" ] || { echo "::error::Missing secret FTP_USERNAME"; missing=1; }
            # Do not echo password value
          [ -n "${{ secrets.FTP_PASSWORD }}" ] || { echo "::error::Missing secret FTP_PASSWORD"; missing=1; }
          [ -n "${{ secrets.FTP_TARGET_DIR }}" ] || { echo "::error::Missing secret FTP_TARGET_DIR"; missing=1; }
          if [ "$missing" -ne 0 ]; then
            echo "One or more required secrets are missing. Add them in GitHub: Settings > Secrets and variables > Actions.";
            exit 1;
          fi
      - name: FTP Deploy
        # Pin to a specific release to avoid 'unable to find version v4' resolution issues
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_TARGET_DIR }}/
          local-dir: dist/aboutus/
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**
